# Generated by Django 5.2.8 on 2025-11-18 10:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0001_initial'),
        ('tickets', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='billing',
            name='ticket_id',
        ),
        migrations.AddField(
            model_name='billing',
            name='ticket',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='billing', to='tickets.ticket'),
        ),
    ]
