# Generated by Django 5.2.8 on 2025-11-19 09:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0002_remove_billing_ticket_id_billing_ticket'),
        ('tickets', '0002_alter_ticket_customer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billing',
            name='ticket',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='billings', to='tickets.ticket'),
        ),
    ]
